name: tika_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.7
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.3.3
  mobile_scanner: ^6.0.2
  device_info_plus: ^10.1.0

  # Gestion des requÃªtes HTTP
  dio: ^5.4.0
  http: ^1.2.0

  # TÃ©lÃ©chargement et gestion de fichiers
  path_provider: ^2.1.2
  open_filex: ^4.5.0
  permission_handler: ^11.3.1

  # ðŸ”¹ Firebase
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.0

  # ðŸ”” Notifications locales
  flutter_local_notifications: ^17.2.4

  # ðŸŒŠ Wave Payment
  uuid: ^4.5.1
  image_picker: ^1.1.2
  http_parser: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # DÃ©claration des images et assets
  assets:
    - lib/core/assets/

# Configuration du splash screen natif - DÃ‰SACTIVÃ‰
flutter_native_splash:
  color: "#FFFFFF"
  android: false
  ios: false
  fullscreen: false
  android_12:
    color: "#FFFFFF"
